apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: thesis2020-tls
spec:
  secretName: thesis2020-kenjifam-fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thesis2020.kenjifam.fi
  dnsNames:
    - thesis2020.kenjifam.fi
    - www.thesis2020.kenjifam.fi
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - thesis2020.kenjifam.fi
          - www.thesis2020.kenjifam.fi
