steps:
  # build test images
  - id: "build-test"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/client-test:$SHORT_SHA",
        "-f",
        "./client/Dockerfile.dev",
        "./client",
      ]

  # run tests
  - id: "run-tests"
    waitFor: ["build-test"]
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "gcr.io/$PROJECT_ID/client-test:$SHORT_SHA",
        "yarn",
        "test:CI",
        "--coverage",
      ]

  # build production images
  - id: "build-server"
    waitFor: ["run-tests"]
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/server:$SHORT_SHA", "./server"]
  - id: "build-client"
    waitFor: ["run-tests"]
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/client:$SHORT_SHA", "./client"]

  # push new images
  - id: "push-server"
    waitFor: ["build-server"]
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/server:$SHORT_SHA"]
  - id: "push-client"
    waitFor: ["build-client"]
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/client:$SHORT_SHA"]

  # deploy to GKE
  - id: "deploy-configs"
    waitFor: ["run-tests"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/configs
      - --output=./configs
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - id: "deploy-server"
    waitFor: ["push-server"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/server-deployment.yaml
      - --image=gcr.io/$PROJECT_ID/server:$SHORT_SHA
      - --output=./server
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - id: "deploy-client"
    waitFor: ["push-client"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/client-deployment.yaml
      - --image=gcr.io/$PROJECT_ID/client:$SHORT_SHA
      - --output=./client
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
timeout: 1800s
