steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/server:$SHORT_SHA", "./server"]
    id: "build-server"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/client:$SHORT_SHA", "./client"]
    id: "build-client"
    waitFor: ["-"]
  # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/server:$SHORT_SHA"]
    id: "push-server"
    waitFor: ["build-server"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/client:$SHORT_SHA"]
    id: "push-client"
    waitFor: ["build-client"]
  # deploy container image to GKE
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #     - run
  #     - --filename=./k8s/mongo-deployment-service.yaml
  #     - --image=mongo
  #     - --location=${_CLOUDSDK_COMPUTE_ZONE}
  #     - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  #   id: "deploy-mongo"
  #   waitFor: ["-"]
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #     - run
  #     - --filename=./k8s/database-persistent-volume-claim.yaml
  #     - --location=${_CLOUDSDK_COMPUTE_ZONE}
  #     - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  #   id: "deploy-pvc"
  #   waitFor: ["deploy-mongo"]
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #     - run
  #     - --filename=./k8s/ingress-service.yaml
  #     - --location=${_CLOUDSDK_COMPUTE_ZONE}
  #     - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  #   id: "deploy-ingress"
  #   waitFor: ["deploy-pvc"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/server-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/server:$SHORT_SHA
      - --output=./server
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
    id: "deploy-server"
    waitFor: ["push-server"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/client-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/client:$SHORT_SHA
      - --output=./client
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
    # id: "deploy-client"
    # waitFor: ["push-client", "deploy-server"]
timeout: 1800s
