steps:
  # build images
  - id: "build-server"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/server:$SHORT_SHA", "./server"]
  - id: "build-client"
    waitFor: ["-"]
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/client:$SHORT_SHA", "./client"]

  # push images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/server:$SHORT_SHA"]
    id: "push-server"
    waitFor: ["build-server"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/client:$SHORT_SHA"]
    id: "push-client"
    waitFor: ["build-client"]

  # deploy to GKE
  - id: "deploy-configs"
    waitFor: ["-"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/configs
      - --output=./configs
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - id: "deploy-server"
    waitFor: ["push-server"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/server-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/server:$SHORT_SHA
      - --output=./server
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - id: "deploy-client"
    waitFor: ["push-client"]
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/client-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/client:$SHORT_SHA
      - --output=./client
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
timeout: 1800s
