steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/server:$SHORT_SHA", "./server"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/client:$SHORT_SHA", "./client"]
  # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/server:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/client:$SHORT_SHA"]
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/server-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/server:$SHORT_SHA
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/client-deployment-service.yaml
      - --image=gcr.io/$PROJECT_ID/client:$SHORT_SHA
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/mongo-deployment-service.yaml
      - --image=mongo
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/database-persistent-volume-claim.yaml
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/ingress-service.yaml
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
