apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.ts": .
        "**/*.tsx": .
    - image: server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.ts": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
