FROM node:13-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN apk add --no-cache make gcc g++ python && \
  yarn install && \
  yarn remove bcrypt && \
  yarn add bcrypt && \
  apk del make gcc g++ python
COPY ./ ./
RUN yarn run build
CMD ["yarn", "run", "dev"]